alphagov/verify-service-provider

src/main/java/uk/gov/ida/verifyserviceprovider/exceptions/JerseyViolationExceptionMapper.java
src/main/java/uk/gov/ida/verifyserviceprovider/exceptions/JsonProcessingExceptionMapper.java
src/main/java/uk/gov/ida/verifyserviceprovider/resources/TranslateSamlResponseResource.java

TT-999 More logging

---

dev-deployment.sh

TT-1000: Add build step back to deploy job

---

dev-deployment.sh
dev-manifest.yml

Moved path to zip file out of manifest and put in shell script
Script finds the most up-to-date version to deploy

TT-1000: Add zip location to command line args

---

dev-manifest.yml

TT-1000: Hopefully let Jenkins use the right buildpack

---

dev-manifest.yml
pen-test-manifest.yml
src/main/resources/verify-service-provider-env.yml

BAU: Add clock skew to manifests

---

src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionTranslator.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/ResponseService.java
src/main/java/uk/gov/ida/verifyserviceprovider/utils/DateTimeComparator.java
src/main/java/uk/gov/ida/verifyserviceprovider/validators/ConditionsValidator.java
src/main/java/uk/gov/ida/verifyserviceprovider/validators/InstantValidator.java
src/main/java/uk/gov/ida/verifyserviceprovider/validators/LevelOfAssuranceValidator.java
src/main/java/uk/gov/ida/verifyserviceprovider/validators/SubjectValidator.java
src/main/java/uk/gov/ida/verifyserviceprovider/validators/TimeRestrictionValidator.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ResponseServiceTest.java

Moved validation into validator classes
Authors: @rachaelbooth @andy-paine

TT-1138 Refactor Assertion Translator

---

src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/VersionNumberResourceTest.java

BAU: Fix mock initialization in tests

---

configuration/verify-service-provider.yml
dev-manifest.yml
pen-test-manifest.yml
src/main/resources/verify-service-provider-env.yml

Increased memory limit
serviceEntityId -> serviceEntityIds to reflect changes
Authors: @rachaelbooth

TT-1227 Updated config for paas deployment

---

README.md

bau: Add a section on responsible disclosure

---

README.md

bau: Simplify instructions for generating private keys

---

docs/adr/0021-we-will-use-http-200-for-valid-saml.md
docs/adr/0023-we-will-report-the-version-in-a-saml-extension.md

TT-1235: Add an ADR for sending the version number

---

README.md

Add more detailed guidance to help users set up Verify Service Provider. Also clarified guidance on the easiest way to configure it.
Written with input from @richardTowers @sgreensmith

Update setup and configuration guidance

---

scripts/init-compliance-tool-for-environment.sh

Includes address history in requested user account creation attributes in compliance tool init script
Authors: @rachaelbooth

TT-1215 Update init compliance tool script

---

docs/api/api-reference.md
docs/tutorial-using-verify-service-provider.md

Verbatim as per Jen's docs:
https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/16J5dibDKvD02hbLuRMC63L3p8fHChSN7KuYFz1dSvV8/edit?usp=sharing
https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1pHFAVtDcwuU40maZpCJmAi7UCkAZ9RvXbFabcdjSi-w/edit?usp=sharing
More updates to come.
Authors: @richardtowers

TT-1430 TT-1431: Add tutorial and API documentation

---

RELEASE_NOTES.md
build.gradle

bau: Update to version 0.4.0 for an ad hoc release

---

docs/adr/0024-release-process-for-verify-service-provider.md

Adding ADR for release process

---

README.md

Added Java 8 and links to MSA documentation to requirements list
Paired: @richardTowers

TT-1575: Add prerequisites

---

docs/tutorial-using-verify-service-provider.md

TT-1575: Add Java 8 and links to MSA documentation to requirements list
Paired with @richardTowers

TT-1575: Clarify requirements for new users

---

README.md

Make it easier for users to find additional documentation and support. 
Author: @J-Lambo

TT-1596: Add links to other documentation

---

build.gradle

BAU: Update dependencies

---

build.gradle

bump from 26 -> 50. No changes to to API.

bau: update to latest saml serializers

---

docs/adr/0025-we-will-only-release-one-configuration-file.md

adr-0024: We will only release one configuration file

---

build.gradle

Co-authored-by: dbes-gds <38218115+dbes-gds@users.noreply.github.com>

VCU-16: Dependency changes for supporting Java 10

---

build.gradle

Gradle build script changes to support multi-release jars.

VCU-20: VSP Multi Release Jar

---

scripts/init-compliance-tool-for-environment.sh

- DO NOT MERGE until [CVQ2 140](https://github.com/alphagov/verify-service-provider/pull/98) has been merged.
- Specify PID in JSON file for non-matching and as an argument for matching.

CVQ2 141 specify pid in json

---

build.gradle

Co-authored-by: <alan.carter@digital.cabinet-office.gov.uk>

BAU: Bump uk.gov.ida:hub-saml to latest version

---

src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnRequestAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAuthnFailedResponseAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingFraudulentMatchResponseAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingNoAuthnContextResponseAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SecondaryEncryptionKeyAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/UserAccountCreationResponseAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/ComplianceToolV1InitialisationRequestBuilder.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/ComplianceToolV2InitialisationRequestBuilder.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/VerifyServiceProviderAppRuleBuilder.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/domain/MatchingAttribute.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/domain/V2MatchingDataset.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/services/ComplianceToolService.java
src/main/java/uk/gov/ida/verifyserviceprovider/resources/TranslateNonMatchingSamlResponseResource.java

All tests pass with status code 200
Created builders for v2 nonmatching to test more efficiently
Added scenario ID's from compliance tool
Created a v2 dataset for nonmatching to test
Co-authored-by: Andy Paine <andy.paine@digital.cabinet-office.gov.uk>

aBHXEwu8: Added acceptance tests for non matching scenarios

---

src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAuthnFailedResponseAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingNoAuthnContextResponseAcceptanceTest.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionService.java

https://trello.com/c/FCLvYDk4/243-non-happy-path-for-non-matching-journey-in-vsp
Solo: @alan-gds

FCLvYDk4: Handle non-matching non-success responses

---

src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAttributes.java
src/main/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapper.java

https://trello.com/c/zjkU3Kyq/245-vsp-to-handle-verified-field-for-gender

zjkU3Kyq: VSP to handle 'verified' field for gender

---

RELEASE_NOTES.md
build.gradle
src/main/java/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderApplication.java
src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/HubMetadataFeatureTest.java
src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataFeatureTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MatchingAssertionServiceTest.java

- This include updating to latest saml-libs which introduces a change to
the metadata healthchecks
- Updated tests to reflect this change and added to the release notes
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>

BAU: Upgrade to OpenSAML 3.4.0

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

- upgrade to gradle 5.1
- upgrade mockito to 2.23.4
- upgrade to latest saml-libs
- Only build with travis against jdk8 and jdk11

bau - Compile successfully against jdk11

---

src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ComplianceToolModeAcceptanceTest.java

Was using the wrong path as a separate change happened that didn't
conflict with this one. (Lesson: Do CI properly)

7DyD3EvQ: fix broken acceptance tests

---

dev-manifest-with-msa.yml

1. Spell service properly :( 
2. Ensure that the correct path to java home is set

YmnUf9Ma: additional manifest fixes

---

Dockerfile.internal
build.gradle

Build the VSP into a docker image.
Solo: @blairboy362

Add a docker image

---

src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java

SSCR: Fix test

---

src/main/java/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataConfiguration.java
src/test/java/uk/gov/ida/verifyserviceprovider/compliance/ComplianceToolModeTest.java
src/test/java/uk/gov/ida/verifyserviceprovider/compliance/RefreshDatasetResourceTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataConfigurationTest.java

Bau code cleanup

---

ci/integration-manifest.yml

BAU: Fix integration manifest

---

configuration/vsp-eidas-without-matching.yml

After the recent changes we need to update the config.

BAU: Update config file schema

---

src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingEidasAcceptanceTest.java
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/AssertionHelper.java
src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/EidasAssertionService.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/EidasAssertionServiceTest.java

https://trello.com/c/IhF99T5e/194-validate-audience
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>

IhF99T5e Fix for bug Validating EIDAS Audience

---

src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResourceTest.java

Checking output of system logging is failing on build environments.
Remove until the issue can be investigated and resolved.

EID-1356: Remove Console Logging Test

---

src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
src/main/java/uk/gov/ida/verifyserviceprovider/resources/TranslateSamlResponseResource.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionService.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionServiceV2.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionService.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/MsaAssertionService.java
src/main/java/uk/gov/ida/verifyserviceprovider/services/ResponseService.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionServiceTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MatchingResponseServiceTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MsaAssertionServiceTest.java

Co-authored-by: Jakub Miarka
<Jakub.Miarka@digital.cabinet-office.gov.uk>

BUGFIX for the startup warning in the VSP

---

RELEASE_NOTES.md
ci/integration-manifest.yml
src/test/resources/verify-service-provider-with-msa-and-eidas.yml

A small addition to `RELEASE_NOTES.md`

EID-1699 update VSP release notes for entityId and unsigned assertions work

---

RELEASE_NOTES.md

Just to separate out the changes as per previous releases.
Also adds a change we should probably include in the release notes.

EID-1718 Reformat release notes

---

build.gradle
configuration/vsp-eidas-without-matching.yml
src/test/resources/verify-service-provider-with-msa-and-eidas.yml

The trust store was wrongly named in a few places.

HUB-697: Fix typos with trust store name

---

RELEASE_NOTES.md
build.gradle

😲 BAU Remove stuff I pushed upstream directly to master

---

RELEASE_NOTES.md
build.gradle
src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SuccessMatchAcceptanceTest.java
src/main/java/uk/gov/ida/verifyserviceprovider/configuration/VerifyServiceProviderConfiguration.java
src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/HubMetadataFeatureTest.java
src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataFeatureTest.java
src/test/java/uk/gov/ida/verifyserviceprovider/compliance/RefreshDatasetResourceTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderConfigurationTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResourceTest.java
src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/TranslateSamlResponseResourceTest.java

Update Dropwizard and the shared test utils.
Change some expected error messages in tests.
Add some `throws Exception`s to test methods
Explicitly add an ObjectMapper that doesn't like unknown properties to a test that needed it.

BAU Upgrade to Dropwizard 2
