alphagov/verify-service-provider

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/InvalidSamlAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NoMatchAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SuccessMatchAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/services/ComplianceToolService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/ResponseService.java
- src/test/java/common/uk/gov/ida/verifyserviceprovider/utils/SamlResponseHelper.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/AttributeTranslationServiceTests.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ResponseServiceTest.java
Handles no match response and added test of user account creation. Refactored acceptance tests
into separate files. Added switch statements for other response status cases.
Authors: @andy-paine @IreneLau-GDS
> TT-877: Handle NO_MATCH response.

- architecture-decisions/verify-service-provider-api.swagger.yml
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnFailedResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ErrorResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/InvalidSamlAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NoAuthnContextResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NoMatchAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SuccessMatchAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/UserAccountCreationResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/services/ComplianceToolService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/LevelOfAssurance.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/TranslateSamlResponseBody.java
- src/main/java/uk/gov/ida/verifyserviceprovider/resources/TranslateSamlResponseResource.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionTranslator.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/ResponseService.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/TranslateSamlResponseResourceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/AssertionTranslatorTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ResponseServiceTest.java
Added a minimum level of assurance field to /translate-response request
Validated that SAML level of assurance was greater than or equal to
requested level of assurance
Authors: @IreneLau-GDS @tunylund @andy-paine
> TT-976: Add level of assurance check to /translate-response endpoint

- build.gradle
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/HubMetadataFeatureTest.java
algorithm restrictions.
Also use property to specify the library version in gradle build
file to ensure consistency.
Authors: @andy-paine @IreneLau-GDS @tunylund
> TT-989 Use the latest saml-metadata-binding library with signing

- architecture-decisions/adr/0017-we-will-pass-the-request-id-to-the-client.md
- architecture-decisions/adr/0020-we-will-put-verified-status-inside-json-object.md
- architecture-decisions/adr/0021-we-will-use-http-200-for-valid-saml.md
Added new ADR to represent decision made on what HTTP status codes to use
Updated previous ADRs that have since been accepted
> BAU: Add ADR for service provider HTTP status codes

- configuration/verify-service-provider-dev.yml
To test integration of local VSP changes with the stub, it is
useful to be able to run the VSP with the same config as on PaaS
This configuration file uses the same 100 year keys as PaaS
Authors: @andy-paine @IreneLau-GDS
> BAU: Added dev configuration file to mirror dev-manifest.yml

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SecondaryEncryptionKeyAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/ComplianceToolInitialisationRequestBuilder.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/VerifyServiceProviderAppRule.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/services/ComplianceToolService.java
Added a test and refactored builder slightly to test that we
can decrypt assertions with our secondary key for when we need to rotate
certs
> TT-1001: Add acceptance test for secondary key for cert rotations

- pre-commit.sh
distZip has been added as a separate step on jenkins
It is not needed in pre-commit anymore
> TT-1000: Remove distZip from pre-commit

- build.gradle
Fetch BUILD_NUMBER using gradle instead of command line args
> TT-1000: Add semver to output version

- build.gradle
- dev-deployment.sh
Added SNAPSHOT to build artifact if BUILD_NUMBER env variable not set
Add a clean step to the dev-deployment so that only one zip file exists
> TT-1000: Add 'SNAPSHOT' and clean on deploy

- dev-deployment.sh
- pre-commit.sh
- scripts/init-compliance-tool.sh
- startup.sh
The cleanup - cd current directory is not necessary for scripts. They
run in subshells, so they can't change the directory of the parent
anyway.
s/CURRENT_DIR/ROOT_DIR/
Authors: @richardtowers
> bau: Tidy shell scripts a bit

- README.md
I think the API should be stable enough not to need warnings now.
Also link to the swagger YAML file from the README.
Authors: @richardtowers
> bau: Remove stability warning from README, link to API docs

- build.gradle
The old version had a transitive dependency on a vulnerable version of
apache beanutils.
See CVE-2014-0114
Authors: @richardtowers
> bau: Upgrade saml-serializers to the latest version

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/UserAccountCreationResponseAcceptanceTest.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/Attributes.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/AttributeTranslationService.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/AttributeTranslationServiceTests.java
Address history can now be sent to RPs as part of user account creation.
This updates the VSP to handle translation of address history attribute when it is present in a user account creation response.
Authors: @rachaelbooth
> TT-1215 Response Translation supports address history

- RELEASE_NOTES.md
To reduce release pain, we ought to be keeping this vaguely up to date as we add features (although it should always be checked over and maybe reworded when it comes to a release). It seems useful to be in the habit of at least adding a bullet point to remind us what features have been added since the last release.
I was going to add support address history in, then figured I may as well look back at the diff and see what else I can catch - I think this is it, but I'm not completely sure I've caught everything that will be user visible. It's based on the diff since the last tag, which also may well not actually match the last release - I'm not sure. This will all be smoother once we've done the first one using the newly discussed process.
> BAU: Update Release Notes

- build.gradle
Making version not to use jenkins build number as it will not be of any significance for RP's who use VSP
Authors: @SKeerthana
> TT-1482 - Changing version number not to use jenkins build number

- README.md
Removed reference to Verify Service Provider handling 'all' communication. 
BECAUSE: users will still need to handle sending AuthnRequests. Verify Service Provider cannot do this for them.
> Clarified role of Verify Service Provider

- build.gradle
- pre-commit.sh
1. Adds gradle plugin to check for available dependency updates.
2. Calls above gradle task in pre-commit to make available dependency updates visible to developers working on the service provider
3. Updates some of the currently out of date dependencies (the easy to do ones...). I've left our saml ones alone since I think Andy said he wants to make some changes during some of those upgrades.
> Library update checker

- build.jenkins
As we'll be using OpenJDK as the basis of our alphagov/java8 build
container on Jenkins2, we need to ensure that VSP will behave as
expected when built in this way.
Note that the build.jenkins in this commit does not contain tag or
publish stages.
Authors: @roryirvine
> BAU: Build on Jenkins2 with OpenJDK

- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/HubMetadataFeatureTest.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataFeatureTest.java
Tests can occasionally fail if something already has the VSP's default
port bound. We can mitigate this failure by overriding this value with 0
in tests, which will give us a random port.
There are some tests that require a specific port for testing the use of
environment variables, but they require a more complicated fix. Expect
a more complicated PR to follow.
> bau: use a random port in tests

- dev-manifest-multi-tenant.yml
- dev-manifest.yml
- local-running/local-config.yml
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/ApplicationConfigurationFeatureTests.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderConfigurationTest.java
- verify-service-provider.yml
Verify Service Provider (VSP) and Matching Service Adaptor (MSA) both perform issue instant validation and they both use clock skew for this validation. MSA's default clockSkew is 30 seconds whereas VSP's default clockSkew is 5 seconds. This change ensures that VSP and MSA have same default clockSkew.
Authors: @adityapahuja
> BAU: Update default clockSkew to PT30s

- .travis.yml
Build-breaker on JDK:oraclejdk10 and JDK:openjdk10.
Enforce Java 10 compatibility on all VSP changes.
> VCU-87: Java 10 builds mandatory in Travis.

- README.md
- build.gradle
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnFailedResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ErrorResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/InvalidSamlAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NoAuthnContextResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NoMatchAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SecondaryEncryptionKeyAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SuccessMatchAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/TranslateResponseMultiTenantedSetupAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/UserAccountCreationResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/VersionNumberAcceptanceTest.java
- verify-service-provider.yml
Upgrade Dropwizard to 1.3.5 to fix various security issues.
Update Dropwizard links to use 1.3.5.
Update all test cases to create an instance of client and initialise it before class to avoid getting uninitialised environment.
Authors: @adityapahuja
> 49: Upgrade Dropwizard to 1.3.5

- docs/api/verify-service-provider-api.swagger.yml
- We have since added `addressHistory` translation to the VSP but
we did not update the swagger docs
- This adds a new array of addresses for `addressHistory`
> Trello-9IPDOHxR: Update swagger API docs with addressHistory

- build.gradle
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/MatchingAssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/validators/AssertionValidator.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ResponseServiceTest.java
- Changed Assertion Service interface into Abstract class. So as to be able to reuse common
functionality.
- Modified Matching Assertion Service class to use AssertionValidator
- Enhanced Non-matching Assertion Service class
- Right now there are 2 constructors in the base really there should be one
> B0ez3pkf validate assertions

- .travis.yml
- This is deprecated according to Travis & Oracle
- See https://www.oracle.com/technetwork/java/javase/eol-135779.html for
more detail
> BAU: Remove Oracle JDK10

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnRequestAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/VerifyServiceProviderAppRule.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/VerifyServiceProviderConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/exceptions/AuthnContextMissingException.java
- src/main/java/uk/gov/ida/verifyserviceprovider/exceptions/NoHashingEntityIdIsProvidedError.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/UserIdHashFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionService.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/ApplicationConfigurationFeatureTests.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderConfigurationTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/saml/UserIdHashFactoryTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionServiceTest.java
- verify-service-provider.yml
- We have left some comments on the `VerifyServiceProviderConfigurationTest.java` to make it easier for the reviewer to understand the `hashingEntityId` scenarios. We can remove these before merging.
- Adds the PID hashing functionality to the VSP as it will happen within here as opposed to the MSA for the non-matching journey.
- The VSP has support for multiple entity IDs (multi-tenanted). We therefore need to know which entity ID to use for hashing in the case of multi tenancy.
The longer version:
What it is?
Add hashing of the PIDs in the VSP as the functionality is currently in the MSA. The MSA currently uses its entity ID as part of the hashing algorithm. The VSP has support for multiple entity IDs (multi-tenanted) so we need to decide which one to hash with.
As most multi-tenanted …
> ss7ycIZj: Hash PIDs in the VSP

- dev-manifest-multi-tenant.yml
- The deployment for the multi-tenanted VSP failed because there was
no hashing entity ID but a list of service entity IDs
- This specifies a hashing entity ID so it can correctly run in
multi-tenanted mode
> BAU: Fix deployment

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionService.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MatchingAssertionServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionServiceTest.java
https://trello.com/c/armQw1ue/246-vsp-to-validate-level-of-assurance
VSP now validates against Level of Assurance using the LevelOfAssuranceValidator
Added unit tests to prove the correct exceptions are being thrown with the new validation
Added another acceptance test to make sure the correct exception is being thrown if loa returned by idp is too low
> armQw1ue: VSP to validate Level Of Assurance

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAuthnFailedResponseAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingNoAuthnContextResponseAcceptanceTest.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/TestTranslatedNonMatchingResponseBody.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/TranslatedNonMatchingResponseBody.java
The TranslatedNonMatchingResponseBody is required by the VSP for deserialization
however when testing it is required to be able to serialise this class. The solution
was to create a test class that inherits TranslatedNonMatchingResponseBody which has
the ability to perform serialisation and use this instead for tests.
Added a TestTranslatedNonMatchingResponseBody
Co-authored-by: olakunle jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
> FIX: Fixed failing tests due to deserialization

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionService.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/NonMatchingAssertionServiceTest.java
The VSP has the capability of Hashing PID for non matching journey,
however this functionality while it is present, is not currently used.
This PR address this by ensuring the non matching assertion service
performs hashing
-implemented test to show nonMatchingAssertionService performs hashing
-hashing functionality called from non assertion service
> Y1qPhJZk: vsp should hash pids in non-matching-assertions

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnRequestAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingEidasAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/AssertionHelper.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/NonMatchingVerifyServiceProviderAppRule.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/VerifyServiceProviderAppRule.java
- src/main/java/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderApplication.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/EuropeanIdentityConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/VerifyServiceProviderConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/SignatureValidatorFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionServiceV2.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/EidasAssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/IdpAssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/MsaAssertionService.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/ApplicationConfigurationFeatureTests.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/HubMetadataFeatureTest.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataFeatureTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderConfigurationTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/EidasAssertionServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/IdpAssertionServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MatchingResponseServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MsaAssertionServiceTest.java
- verify-service-provider.yml
https://trello.com/c/JhIrB3HL/266-eidas-functionality-for-the-vsp
This work was originally done on the https://github.com/alphagov/verify-service-provider/tree/JhIrB3HL_eidas-non-matching-journey branch, and is broken down a bit more there (although not very coherently, at least in the case of the commits I authored).
The work includes adding configuration necessary for validating and interpreting eIDAS assertions (in particular, so the necessary metadata and trust anchor can be found).  A new ClassifyingAssertionService class deals with working out whether a Response is from an IDP or eIDAS; it then delegates to an assertion service class tailored for one or the other.
Some of the new classes in this work have not been named well; I'm going to resolve that in a subsequent task.  Also, …
> JhIrB3HL: eIDAS non matching journey

- integration-deployment.sh
- integration-manifest.yml
This adds a new deployment script and manifest specific to
integration connection. It removes the private keys from manifest
and set them as env variables. The keys are supplied as secrets by Jenkins.
The script along with the deployment pipeline should be refactored to be
simpler with less duplication - I raised a ticket for it
https://trello.com/c/MOIRqsXG/68-refactor-vsp-deployment-pipeline
> rMMKhjYc: Run VSP in PaaS connected to integration

- README.md
The old doc we linked to just redirected us to the new doc.
> BAU: Update link to API reference doc

- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/ComplianceToolMode.java
The file option is never used in development mode so I've removed it as an option to development mode.
> 7DyD3EvQ: remove unused file option from Development mode

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingScenario.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/AssertionServiceV2.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/IdpAssertionService.java
- The VSP has always returned CANCELLATION in response to NOAUTHNCONTEXT, but this was a mistake.
- For a non-matching journey, we will now return NO_AUTHENTICATION in that scenario.
_ For backwards compatibility, the matching journey will continue to return CANCELLATION.
https://trello.com/c/2uk41vWL/71-vsp-should-return-noauthentication-instead-of-cancellation-as-a-possible-scenario-in-its-responses
> 2uk41vWL: return NO_AUTHENTICATION for NOAUTHNCONTEXT

- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/ComplianceToolMode.java
- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/IdentityDatasetArgumentResolver.java
- src/main/resources/default-test-identity-dataset.json
- src/test/java/uk/gov/ida/verifyserviceprovider/compliance/ComplianceToolModeTest.java
What
=====
use a file to store the devmode default identity dataset so it can be easily referenced in READMEs and other guides.
Also, provide a reference tn the docs to find out more about the default identity dataset as it's too large to include in the CLI.
Finally, rename the CLI option of --matchingDataset to --identityDataset
We have chosen identityDataset as it better reflects the domain (i.e. where matching is independent of the VSP and Hub).
> Improve description of default matching dataset

- build.gradle
- dev-manifest-with-msa.yml
The distribution was being built without the vsp application.
Protip: unzip your zips
> YmnUf9Ma: fix the building of testing dist

- build.gradle
When running on Java 11 the following dependency is needed:
```
javax.activation:javax.activation-api:1.2.0
```
Otherwise when you start the VSP there are lots of warning messages
related to:
```
java.lang.NoClassDefFoundError: javax/activation/DataSource
```
> qQOLcfG7: Add missing dependency on Java11

- .dockerignore
- Dockerfile.internal
- Gradle install fails the docker build and was meant to greedily cache
the dependencies but doesn't do that
- This repository is fairly small so the build is quick anyway
- Also add a .dockerignore to make builds faster as we don't have to
push the whole context to the docker daemon
> BAU: Remove failing task from Dockerfile

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ComplianceToolModeAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/Utils/MdsValueChecker.java
- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/dto/MatchingAttribute.java
- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/dto/MatchingDataset.java
- src/test/java/uk/gov/ida/verifyserviceprovider/compliance/dto/MatchingDatasetBuilder.java
When the VSP runs in development mode we need to be able to have some
support for eIDAS identities. An eIDAS identity will have attributes that
are missing `from` and `to` dates. Some attributes may also be absent.
This change includes tests and changes to how the Dto that is sent
to CT, and contains the identity, serializes itself.
> fix: support for eidas identities in development mode

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/ComplianceToolV2InitialisationRequestBuilder.java
- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/dto/MatchingDataset.java
- src/main/resources/default-test-identity-dataset.json
- src/test/java/uk/gov/ida/verifyserviceprovider/compliance/dto/MatchingDatasetBuilder.java
We forgot to include the LevelOfAssurance in the DTO for the matching dataset used to initiate the Compliance Tool when running the VSP in development mode.
> NjRC8QiD: Add LOA to Compliance Tool MDS

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ComplianceToolModeAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/Utils/MdsValueChecker.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAddress.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAttributes.java
- src/main/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapper.java
- src/test/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingVerifiableAttributeBuilder.java
- src/test/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapperTest.java
The SAML profile specified that attribtue should be provided as a list with historical context, but we were ignoring this and only returning the first of some attributes (firstName, and Date Of Birth). In some case this could cause problems if a non-verified attribute was returned when a verified attribute was available.
This PR changes the attributes returned to make them more consistent with the SAML profile.
The following attributes will now be provided with possible historical values:
- firstNames
- middleNames
- surnames
- dates Of Birth
- addresses
Gender will still be provided as a single attribute.
>  zEyIoEnS: Return most attributes with their historical values

- .gitignore
- Dockerfile.internal
In some circumstances the artifactory repo isn't available (proxy-node) and so we need the option to fall back to the public ones.
Solo: @blairboy362
> Allow external binaries in docker build

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ComplianceToolModeAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/Utils/MdsValueChecker.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAddress.java
- src/main/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapper.java
- src/test/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapperTest.java
Addresses from our IDPs may include a UPRN field, but the VSP is currently ignoring it in our response back to the service. We should include it as it may be helpful to a service.
The UPRN could be used by a service to assist with matching or other reasons.
> OLqSibaL: Add UPRN to Addresses returned by the VSP

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ComplianceToolModeAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/Utils/MdsValueChecker.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingVerifiableAttribute.java
- src/main/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapper.java
- src/test/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingVerifiableAttributeBuilder.java
- src/test/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapperTest.java
The from/to dates in NonMatchingVerifiableAttribute should be LocalDates, not LocalDateTimes.  The time component is not useful.
> gUPcguib: Use LocalDate instead of LocalDateTime

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingEidasAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/AssertionHelper.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAttributes.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingTransliterableAttribute.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/TestTranslatedNonMatchingResponseBody.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/TranslatedNonMatchingResponseBody.java
- src/main/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapper.java
- src/test/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapperTest.java
This PR adds support for serializing the `nonLatinScriptValue` from eIDAS Assertions into the attributes returned from the VSP.
> 9ZNOyJJW: include nonLatinScriptValue on name attributes

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/NonMatchingVerifyServiceProviderAppRule.java
- src/main/java/uk/gov/ida/saml/metadata/EidasMetadataConfigurationImpl.java
- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/ComplianceToolModeConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/ConfigurationConstants.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/EuropeanIdentityConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/HubEnvironment.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/VerifyHubConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/VerifyServiceProviderConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/ApplicationConfigurationFeatureTests.java
- src/test/java/uk/gov/ida/verifyserviceprovider/configuration/EuropeanIdentityConfigurationTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderConfigurationTest.java
- verify-service-provider.yml
- Support for EIDAS is based on whether the VSP has an EIDAS configuration
- EIDAS service is enabled when it flag is set to true
- Added tests for the above
Co-authored-by: Amrit Sidhu <amrit.sidhu@digital.cabinet-office.gov.uk>
> f7X3GoiN: configure the vsps eidas functionality using its hub environment config property

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingAcceptanceTest.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/TranslatedNonMatchingResponseBody.java
When a scenario is anything other than IDENTITY_VERIFIED the `pid`,
`levelOfAssurance`, and `attributes` are currently being serialized as
nulls. Instead, we should not serialize them at all.
> fix: don't serialize some null fields

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnRequestAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/ComplianceToolModeAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/services/GenerateRequestService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/dto/RequestGenerationBody.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/AuthnRequestFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResource.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/EntityIdService.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/factories/saml/AuthnRequestFactoryTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResourceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/EntityIdServiceTest.java
This parameter isn't used for anything so we can make it optional with
a view to phasing it out (or doing something with it) in the next
release.
It should be able to handle empty request bodies, '{}', and
'{"entityId": "foobar"}' bodies.
Also, removed the passing of 'levelOfAssurance' to objects where it's
never used.
Note: we've removed this parameter from our docs so if we don't remove it now then we need to fix the docs.
> bau: make loa request param optional

- RELEASE_NOTES.md
- build.gradle
There's a minor release that fixes a few things and includes a few CVEs. Release notes are [here](https://github.com/dropwizard/dropwizard/blob/v1.3.9/docs/source/about/release-notes.rst).
> bau: upgrade to latest dropwizard

- build.gradle
- src/main/java/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderApplication.java
- src/main/java/uk/gov/ida/verifyserviceprovider/logging/AuthnRequestAttributesHelper.java
- src/main/java/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResource.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResourceTest.java
- src/test/resources/logback-test.xml
Extra Attributes will be logged at info level for all VSP users.
Service VSP users will NOT see the logging format changed to json as this requires a config change that will only be applied in the Eidas Proxy Node.
> EID-1356:  Log AuthnRequest Attributes in the VSP using MDC

- README.md
There is up to date documentation on the VSP's API which should be correctly linked to in the README:
- [OpenAPI v3 specification](https://github.com/alphagov/verify-service-provider/blob/master/docs/api/verify-service-provider-api.swagger.yml)
- [Reference documentation in a more human readable HTML format](https://alphagov.github.io/verify-service-provider/api/verify-service-provider-api.swagger.html)
The PR adds links to these API resources.
> Update README links to VSP API documentation

- ci/dev-manifest-multi-tenant.yml
- ci/dev-manifest.yml
The PaaS stack image cflinuxfs2 is being deprecated and needs to be
replace with cflinuxfs3 by end of April 2019.
> BAU: Upgrade PaaS stack to cflinuxfs3

- ci/staging-manifest.yml
For the self-service app testing, we're deploying the test service to
the staging environment. The config for PaaS deployment includes the
environment variables required for the connection.
Concourse config changes: https://github.com/alphagov/verify-terraform/pull/936
Hub config changes: https://github.com/alphagov/verify-hub-federation-config/pull/357
> vGSUtQgY: Add staging manifest

- build.gradle
- configuration/vsp-with-matching-custom.yml
VSP is now configured using VERIFY_ENVIRONMENT env variable. With options
(COMPLIANCE_TOOL, INTEGRATION, PRODUCTION). However, we want to
run in the staging environment. So we need to override the `ssoLocation` and `metadata URI`
which should be enough to repoint the VSP to staging.
The custom config file is only used in PaaS when connecting to staging.
> vGSUtQgY: Add a new config which allows for overriding hub env values

- ci/production-manifest.yml
We need a product version of the VSP in the hub for testing against this change creates a new configuration file for the VSP for production.
> DEUtoBzK Added new production manifest to the VSP

- build.gradle
This allows the app to be configured to format the app and request logs as JSON.
This is needed for the VSP instance used by the Proxy Node, as explained in alphagov/verify-proxy-node#227
> EID-1508: Add Dropwizard json logging library

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/NonMatchingVerifyServiceProviderAppRule.java
- src/test/java/common/uk/gov/ida/verifyserviceprovider/servers/MockMetadataAggregatorServer.java
- src/test/java/common/uk/gov/ida/verifyserviceprovider/servers/MockTrustAnchorServer.java
- src/test/java/common/uk/gov/ida/verifyserviceprovider/servers/MockVerifyHubServer.java
This replaces some usages of HTTPStubRule with wiremock which is our preferred library for mock HTTP services.
> Remove use of http stub rule

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/rules/VerifyServiceProviderAppRule.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/VerifyServiceProviderConfiguration.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/MsaMetadataFeatureTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/VerifyServiceProviderConfigurationTest.java
- src/test/resources/verify-service-provider-with-msa-and-eidas.yml
This change adds a constraint to the VSP's config so that the `europeanIdentity` and `msa` configuration can't be set at the same time. Setting this behavior together shouldn't work as the two modes are mutually exclusive. eIDAS support on the VSP is only needed when its acting in a standalone capacity.
> PeUHqcqv: constraint to stop eIDAS and MSA config being set together

- README.md
- src/main/java/uk/gov/ida/verifyserviceprovider/compliance/RefreshDatasetResource.java
- src/test/java/uk/gov/ida/verifyserviceprovider/compliance/RefreshDatasetResourceTest.java
Previously, we agreed to refer to the dataset returned by the standalone VSP
as the identity dataset. This change updates a resource in development
mode to follow the same naming convention. It also fixes a mistake in
the README which used the wrong name for a command line option
> fix: Use consistent naming for identity dataset

- .travis.yml
- README.md
- build.gradle
Report test coverage to Codacy.
Only run the coverage report on JDK 9 and later as the plugin doesn't work Java 8.
> BAU: Add Codacy test coverage reporting

- build.gradle
We don't need to depend on `hub-saml`.
We should be using the unified `saml-lib` library rather than separate libs.
> BAU: Update dependencies

- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/ConfigurationConstants.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/EuropeanIdentityConfiguration.java
- src/main/java/uk/gov/ida/verifyserviceprovider/configuration/HubEnvironment.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/EidasAssertionTranslator.java
- src/test/java/feature/uk/gov/ida/verifyserviceprovider/configuration/ApplicationConfigurationFeatureTests.java
- src/test/java/uk/gov/ida/verifyserviceprovider/configuration/EuropeanIdentityConfigurationTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/EidasAssertionTranslatorTest.java
This PR:
- ... makes the `hubConnectorEntityId` configuration option nullable.
- ... updates the subdomain ordering in the potential new entityIds.
- ... removes `getHubConnectorId()` in favour of `getAllAcceptableHubConnectorIds()`.
> EID-1683 make hubConnectorEntityId optional

- build.gradle
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/NonMatchingEidasAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/AssertionHelper.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/builders/ComplianceToolV2InitialisationRequestBuilder.java
- src/main/java/uk/gov/ida/verifyserviceprovider/exceptions/MissingUnsignedAssertionsHandlerException.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/VerifyServiceProviderFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/factories/saml/ResponseFactory.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/BaseEidasAssertionTranslator.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionTranslator.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/EidasAssertionTranslator.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/EidasUnsignedAssertionTranslator.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/ResponseService.java
- src/main/java/uk/gov/ida/verifyserviceprovider/services/UnsignedAssertionsResponseHandler.java
- src/main/java/uk/gov/ida/verifyserviceprovider/validators/EidasAssertionTranslatorValidatorContainer.java
- src/main/java/uk/gov/ida/verifyserviceprovider/validators/EidasEncryptionAlgorithmValidator.java
- src/main/java/uk/gov/ida/verifyserviceprovider/validators/EidasEncryptionAlgorithmValidatorHelper.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/resources/GenerateAuthnRequestResourceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/saml/ResponseFactoryTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/BaseEidasAssertionTranslatorTestBase.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ClassifyingAssertionTranslatorTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/EidasAssertionTranslatorTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/EidasUnsignedAssertionTranslatorTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/MatchingAssertionTranslatorTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/ResponseServiceTest.java
- src/test/java/unit/uk/gov/ida/verifyserviceprovider/services/UnsignedAssertionResponseHandlerTest.java
If you want to run the VSP locally so you can debug it, there are a couple of branches which will help. These are by no means meant to be a good way to run it, it's just how I hacked it together when developing this PR. Use these branches locally and then run `./hubstartup.sh` in `ida-hub-acceptance-tests`
https://github.com/alphagov/ida-hub-acceptance-tests/tree/test-rp-vsp
https://github.com/alphagov/verify-test-rp/tree/non-matching
You'll also need to cherry pick the last commit from this branch of the VSP, which adds a local config: https://github.com/alphagov/verify-service-provider/tree/eid-1607
It includes a few updates including making it easier to create a
decrypter for unsigned assertions.
The ResponseService needs to be able to determine if the incoming
Response has unsigned …
> EID-1607 Handle unsigned assertions

- .dockerignore
This is so we can build local docker images of the VSP using binaries built locally instead of building them in docker every time
This is needed for the Proxy Node local startup to work
> BAU: Include local binaries in docker workspace

- .dockerignore
This used to be so we could build local docker images of the VSP using binaries built locally instead of building them in docker every time.
This used to be needed for the Proxy Node local startup to work but now we mount the bins so they don't need to be included in Docker context. This makes docker build run faster.
This is the result of alphagov/verify-proxy-node#583
> BAU: Revert including local binaries in docker workspace

- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/AuthnRequestAcceptanceTest.java
- src/acceptance-test/java/uk/gov/ida/verifyserviceprovider/SuccessMatchAcceptanceTest.java
* Adds a number of additional tests to `SuccessMatchAcceptanceTest` for errors that `translate-response` can generate.
* Adds some assertions to `AuthnRequestAcceptanceTest` to illustrate that the `requestId` is always generated.
> Test errors for incorrectly crafted translation requests

- RELEASE_NOTES.md
- build.gradle
This version includes a fix for a bug where metadata resolvers were not
picking up on changes to a countries trust-anchor.
> BAU: Upgrade saml-libs to 249

- Dockerfile.internal
This is a small update to the Dockerfile to bump the versions of Gradle and JDK we use.
> HUB-708 Update Dockerfile to use JDK11

- Dockerfile.internal
Update the Dockerfile to use images from GitHub container registry rather than having them come from DockerHub.
> HUB-774 Update Dockerfile to use GHCR

- Dockerfile.internal
- RELEASE_NOTES.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- pre-commit.sh
Remove unloved versions plugin.
Remove unused idea plugin.
Update dockerfile to use a base image with version 6.8.3. The vendored
image has slipped to version 7 which doesn't work.
Update public builds to use maven central and bump versions of
dependencies to ensure the maven central artifacts are being used.
Update gradle to 6.8.3
> HUB-914: Pull from maven central

- Dockerfile.internal
- startup.sh
The decision was made to use a paid Docker Hub account in the pipeline rather than GitHub packages after the move previously to github packages when Docker Hub imposed rate limit restrictions.
- Removed `USER root` and swapped to using `USER gradle`. The [base image](https://github.com/keeganwitt/docker-gradle/blob/019489a1187aac1788f5369048c34969462a0456/hotspot/jdk11/Dockerfile) creates a user called gradle but never swaps to it. It symlinks root cache too. We shouldn't in theory have any reason to use root with this container, granted it's only a building layer but personally I think it's better to use non-root. Given `WORKDIR` doesn't let you clarify which user to create the folder with I've had to create the folder first and `chown` it. Likewise with the `COPY` commands which also …
> [HUB-841] Update dockerfiles to use dockerhub again.

- .travis.yml
- RELEASE_NOTES.md
- build.gradle
Update logback to 1.2.9 to mitigate CVE-2021-42550
See the article "16th of December, 2021, Release of version 1.2.9" at http://logback.qos.ch/news.html
> BAU Update logback to 1.2.9

- build.gradle
- xmlsec and commons-collections are both brought in by opensaml. We want to override the version brought in my opensaml.
> BAU - Force version of xmlsec to 2.1.8
